version: '3.7'

services:
  parser-db:
    container_name: parser-db
    image: postgres:15.1-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - parser-db-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:54322:5432
    networks:
      - parser-net

volumes:
  parser-db-data:

networks:
  parser-net:
